version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    restart: always
    environment:
      - discovery.type=single-node
      - http.port=9200
      - transport.port=9300
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
  elasticsearch-mapping-init:
    build: .
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - ELASTICSEARCH_ENVS=dev uat prod
      - ELASTICSEARCH_URL=elasticsearch:9200
    volumes:
      - ./mapping.json:/mapping.json
    restart: on-failure
    links:
      - elasticsearch
